## 1. Load the Dataset

In [7]:
import pandas as pd

df = pd.read_csv("data.csv")
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

## 2. Check Dataset Information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

## 3. Check Missing Values

In [9]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

## 4. Handle Missing Values

In [10]:
df["Calories"] = df["Calories"].fillna(df["Calories"].mean())
df["Date"] = df["Date"].fillna("Unknown")

df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

## 5. Filter Rows

In [11]:
filtered_df = df[df["Calories"] > 400]

filtered_df

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
4        45  '2020/12/05'    117       148     406.0

## 6. Create a New Column

In [12]:
df["Calories_per_Duration"] = df["Calories"] / df["Duration"]

df.head()

   Duration          Date  Pulse  Maxpulse  Calories  Calories_per_Duration
0        60  '2020/12/01'    110       130     409.1               6.818333
1        60  '2020/12/02'    117       145     479.0               7.983333
2        60  '2020/12/03'    103       135     340.0               5.666667
3        45  '2020/12/04'    109       175     282.4               6.275556
4        45  '2020/12/05'    117       148     406.0               9.022222

## 7. Results

- Missing values were handled successfully.
- Rows with Calories greater than 400 were filtered.
- A new `Calories_per_Duration` column was created.